# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0002_auto_20151204_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgusername', models.TextField(max_length=50)),
                ('sgpassword', models.TextField(max_length=50)),
            ],
        ),
    ]
