# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20151207_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statdate', models.DateField(auto_now=True)),
                ('pa_invvalue', models.FloatField()),
                ('pa_count30to45', models.IntegerField()),
                ('pa_count60to65', models.IntegerField()),
                ('sv_ro_count', models.IntegerField()),
                ('sv_old_ro_count', models.IntegerField()),
            ],
        ),
    ]
